import './globals.css';

import localFont from 'next/font/local';
import Link from 'next/link';

import { Providers } from '@/components/providers';

import type { Metadata } from 'next';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://unpkg.com/react-scan/dist/auto.global.js"
          async
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="flex gap-4">
          <Link href={'/'}>Home</Link>
          <Link href={'/todo'}>Todo</Link>
          <Link href={'/react-query'}>React Query</Link>
          <Link href={'/theme'}>Theme</Link>
        </nav>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
