import './globals.css';

import Link from 'next/link';

import { Providers } from '@/components/providers';
import { geistMono, inter } from '@/lib/fonts';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://unpkg.com/react-scan/dist/auto.global.js"
          async
        />
      </head>
      <body className={`${inter.variable} ${geistMono.variable} antialiased`}>
        <nav className="flex gap-4">
          <Link href={'/'}>Home</Link>
          <Link href={'/todo'}>Todo</Link>
          <Link href={'/react-query'}>React Query</Link>
          <Link href={'/theme'}>Theme</Link>
        </nav>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
